//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.con_ORDERPROC_DOCTOR = new HashSet<con_ORDERPROC_DOCTOR>();
            this.Doc_Insurance_Affiliation = new HashSet<Doc_Insurance_Affiliation>();
            this.Doc_Specialties_Profile1 = new HashSet<Doc_Specialties_Profile>();
            this.Doc_Education = new HashSet<Doc_Education>();
            this.Doc_Insurance = new HashSet<Doc_Insurance>();
        }
    
        public long id { get; set; }
        public string doctor_name { get; set; }
        public string gender { get; set; }
        public string title { get; set; }
        public string doctor_phone { get; set; }
        public string doctor_fax { get; set; }
        public string doctor_NPI { get; set; }
        public string doctor_NPI_type { get; set; }
        public string doctor_org_name { get; set; }
        public Nullable<long> doctor_rel_ADDRESS_id { get; set; }
        public string doctor_state_m_id { get; set; }
        public string doctor_medicare_upin { get; set; }
        public string doctor_license_no { get; set; }
        public Nullable<bool> doctor_pecos_cert { get; set; }
        public string doctor_fax_to { get; set; }
        public string doctor_address1 { get; set; }
        public string doctor_address2 { get; set; }
        public string doctor_address_state { get; set; }
        public string doctor_address_city { get; set; }
        public string doctor_address { get; set; }
        public string doctor_address_zip { get; set; }
        public Nullable<long> last_update_by { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<int> status { get; set; }
        public string doctor_specialty { get; set; }
        public string image_url { get; set; }
        public Nullable<long> specialty_id { get; set; }
        public string bio { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<con_ORDERPROC_DOCTOR> con_ORDERPROC_DOCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_Insurance_Affiliation> Doc_Insurance_Affiliation { get; set; }
        public virtual Doc_Specialties_Profile Doc_Specialties_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_Specialties_Profile> Doc_Specialties_Profile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_Education> Doc_Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_Insurance> Doc_Insurance { get; set; }
    }
}
