//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTE
    {
        public long id { get; set; }
        public string text { get; set; }
        public long written_by { get; set; }
        public System.DateTime written_on { get; set; }
        public string note_type { get; set; }
        public Nullable<long> rel_ref_note_type_id { get; set; }
        public Nullable<long> rel_parent_id { get; set; }
        public string tags { get; set; }
    }
}
