//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOUL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOUL()
        {
            this.con_LIST_SOUL = new HashSet<con_LIST_SOUL>();
            this.con_ORDERPROC_DOCTOR = new HashSet<con_ORDERPROC_DOCTOR>();
            this.con_SOUL_ref_upsell = new HashSet<con_SOUL_ref_upsell>();
        }
    
        public long id { get; set; }
        public string name_first { get; set; }
        public string name_last { get; set; }
        public string phone_number { get; set; }
        public long rel_ADDRESS_id { get; set; }
        public string email { get; set; }
        public string meta { get; set; }
        public string OR_LIST_res_code { get; set; }
        public Nullable<System.DateTime> last_contact { get; set; }
        public Nullable<long> last_contact_by { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<long> last_update_by { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string alt_name { get; set; }
        public string alt_phone { get; set; }
        public string alt_relationship { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<con_LIST_SOUL> con_LIST_SOUL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<con_ORDERPROC_DOCTOR> con_ORDERPROC_DOCTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<con_SOUL_ref_upsell> con_SOUL_ref_upsell { get; set; }
    }
}
